Revert "hwc: Use layerIndex while populating hw layers"
Causing a CTS fail:

05-25 16:38:51 I/4666c48a:com.android.cts.jank.opengl.CtsHostJankOpenGl#testPixelOutput FAIL
junit.framework.AssertionFailedError: Could not parse the results file: expected:<4> but was:<0>

This reverts commit bd9e66710bec76c16d8d45a6c1a4b58691a391a7.

Change-Id: Ia72f4dfdc9382bf1599603c23368aa3f6ccecd71